### ISSUE TITLE
... 

### ISSUE THREAD

**Issue by JeninSutradhar** [aagedal/fibonacci#1]
great work! Have you considered exploring Slint UI framework for Rust? It could enhance the user experience and add a polished interface to your project
Take a look https://github.com/JeninSutradhar/Slint-rust-gui-application

**Comment by aagedal** [comment]
> great work! Have you considered exploring Slint UI framework for Rust? It could enhance the user experience and add a polished interface to your project
> Take a look https://github.com/JeninSutradhar/Slint-rust-gui-application 

Thanks! I am actually working on another project using Slint UI.
